language: node_js
node_js:
  - 9
# @TODO: fix sudo workaround
# https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356362524
sudo: required
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - npm run test
script:
  - npm run build
